# Banking Operations Intelligence Solution

## Data Generation Notebook

This notebook generates synthetic data for the Banking Operations Intelligence Solution.

In [140]:
import pandas as pd
import random
from datetime import datetime, timedelta
from faker import Faker
import string
fake = Faker()

In [141]:
branches = [
    [1, "Kampala Main", "Kampala Road", "Kampala", "Grace Namusoke", "Central"],
    [2, "Kingdom Kampala", "Kingdom Mall", "Kampala", "Peter Okello", "Central"],
    [3, "Acacia", "Acacia Avenue", "Kampala", "Sarah Nankya", "Central"],
    [4, "Nansana", "Nansana Town", "Kampala", "Brian Kato", "Central"],
    [5, "Jinja", "Main Street", "Jinja", "Ruth Nabirye", "Eastern"],
    [6, "Tororo", "Tororo Town", "Tororo", "David Ochan", "Eastern"],
    [7, "Soroti", "Soroti Town", "Soroti", "Esther Acom", "Eastern"],
    [8, "Mbarara", "High Street", "Mbarara", "Michael Tumusiime", "Western"],
    [9, "Fort Portal", "Rwenzori Road", "Fort Portal", "Joan Akiiki", "Western"],
    [10, "Hoima", "Main Street", "Hoima", "Isaac Atwine", "Western"],
    [11, "Kasese", "Kilembe Road", "Kasese", "John Baluku", "Western"],
    [12, "Gulu", "Gulu Main Street", "Gulu", "Alice Acen", "Northern"],
    [13, "Lira", "Oyam Road", "Lira", "Robert Ocen", "Northern"]
]

In [142]:
branch_columns = [
    "BranchID",
    "BranchName",
    "Address",
    "City",
    "BranchManager",
    "Region"
]

dim_branch = pd.DataFrame(branches, columns=branch_columns)

In [143]:
dim_branch

,BranchID,BranchName,Address,City,BranchManager,Region
0,1,Kampala Main,Kampala Road,Kampala,Grace Namusoke,Central
1,2,Kingdom Kampala,Kingdom Mall,Kampala,Peter Okello,Central
2,3,Acacia,Acacia Avenue,Kampala,Sarah Nankya,Central
3,4,Nansana,Nansana Town,Kampala,Brian Kato,Central
4,5,Jinja,Main Street,Jinja,Ruth Nabirye,Eastern
5,6,Tororo,Tororo Town,Tororo,David Ochan,Eastern
6,7,Soroti,Soroti Town,Soroti,Esther Acom,Eastern
7,8,Mbarara,High Street,Mbarara,Michael Tumusiime,Western
8,9,Fort Portal,Rwenzori Road,Fort Portal,Joan Akiiki,Western
9,10,Hoima,Main Street,Hoima,Isaac Atwine,Western
10,11,Kasese,Kilembe Road,Kasese,John Baluku,Western
11,12,Gulu,Gulu Main Street,Gulu,Alice Acen,Northern
12,13,Lira,Oyam Road,Lira,Robert Ocen,Northern

##  Generate Employee Dimension

In [144]:
fake = Faker()

employee_data = []

employee_id = 1

In [145]:
male_first_names = [
    "Fred","Brian","Peter","David",
    "Michael","Robert","Isaac", "Benard",
    "Kelvin","Daniel","Joseph","Paul",
   "Patrick","Emmanuel", "Mark","Andrew","Simon"
]
female_first_names = [
    "Grace","Sarah","Ruth", "Julliette",
    "Saubah","Alice","Joanne", "Peace",
    "Aisha","Danielle","Esther","Dawn", "Lesley", 
    "Sharon","Lydia","Sheibah", "Gladys",
    "Lisa","Rebecca","Elliana", "Ayebare", "Tracy"
]
male_last_names = [
    "Musoke","Wasswa","Mutabazi","Okello",
    "Isabirye","Tumusiime","Amooti","Baluku",
    "Ocen","Atwine","Mugisha",
    "Muhwezi","Byaruhanga","Ssemanda",
    "Onyango","Ouma","Zziwa","Nyombi", "Nkalubo", "Tenywa"
]

female_last_names = [
    "Namusoke","Nakato","Nankya","Akello","Onyango",
    "Nabirye","Tusiime","Akiiki","Biira", 
    "Acen","Mwebaza","Atwine","Mugisha",
    "Kyomuhendo","Byakatonda","Namanda",
    "Auma","Ankunda", "Galiwango"
]

In [146]:
# Number of employees per branch
branch_distribution = {
    1: 12,   # Kampala Main
    2: 8,    # Kingdom Kampala
    3: 7,    # Acacia
    4: 5,    # Nansana
    5: 5,    # Jinja
    6: 4,    # Tororo
    7: 3,    # Soroti
    8: 5,    # Mbarara
    9: 2,    # Fort Portal
    10: 3,   # Hoima
    11: 2,   # Kasese
    12: 5,   # Gulu
    13: 4    # Lira
}

In [147]:

# Starting employee number
employee_number = 401

# Used email
used_emails = set()

# Generate employees
for branch_id, number_of_employees in branch_distribution.items():

    for i in range(number_of_employees):

        # Random names
        gender = random.choice(["Male","Female"])
        first_name = random.choice(male_first_names if gender == "Male" else female_first_names)
        last_name = random.choice(male_last_names if gender == "Male" else female_last_names)

        # Employee ID
        employee_id = f"UB{employee_number:04d}{random.choice(string.ascii_uppercase)}"

        # Email and incase of duplicate email
    
        email = f"{first_name.lower()}.{last_name.lower()}{employee_number}@unitybank.co.ug"
     

        # Role
        role = random.choices(
            [
                "Account Maintenance Officer",
                "Senior Account Maintenance Officer",
                "Team Leader",
                "Operations Manager"
            ],
            weights=[45,10,7,3],
            k=1
        )[0]

        # Hire Date
        hire_date = fake.date_between(
            start_date="-6y",
            end_date="today"
        )

        # Employee Status
        status = random.choices(
            ["Active","Inactive"],
            weights=[95,5],
            k=1
        )[0]

        # Store employee record
        employee = [
            employee_id,
            first_name,
            last_name,
            email,
            role,
            branch_id,
            hire_date,
            status
        ]

        # Add employee to list
        employee_data.append(employee)

        # Increment employee number
        employee_number += 1

# Create DataFrame
dim_employee = pd.DataFrame(
    employee_data,
    columns=[
        "EmployeeID",
        "FirstName",
        "LastName",
        "Email",
        "Role",
        "BranchID",
        "HireDate",
        "EmployeeStatus"
    ]
)
branch_distribution.values()

dict_values([12, 8, 7, 5, 5, 4, 3, 5, 2, 3, 2, 5, 4])

In [148]:
# Preview the data
dim_employee

,EmployeeID,FirstName,LastName,Email,Role,BranchID,HireDate,EmployeeStatus
0,UB0401U,Mark,Wasswa,mark.wasswa401@unitybank.co.ug,Senior Account Maintenance Officer,1,2023-05-21,Inactive
1,UB0402T,Robert,Mugisha,robert.mugisha402@unitybank.co.ug,Senior Account Maintenance Officer,1,2023-04-08,Active
2,UB0403W,Sarah,Galiwango,sarah.galiwango403@unitybank.co.ug,Operations Manager,1,2022-04-15,Inactive
3,UB0404Z,Paul,Nyombi,paul.nyombi404@unitybank.co.ug,Account Maintenance Officer,1,2025-09-28,Active
4,UB0405L,Peter,Onyango,peter.onyango405@unitybank.co.ug,Senior Account Maintenance Officer,1,2025-03-05,Active
...,...,...,...,...,...,...,...,...
60,UB0461I,Esther,Nabirye,esther.nabirye461@unitybank.co.ug,Account Maintenance Officer,12,2024-04-02,Active
61,UB0462B,Aisha,Namusoke,aisha.namusoke462@unitybank.co.ug,Account Maintenance Officer,13,2026-04-04,Active
62,UB0463O,Peter,Ouma,peter.ouma463@unitybank.co.ug,Account Maintenance Officer,13,2024-09-13,Active
63,UB0464W,Saubah,Nankya,saubah.nankya464@unitybank.co.ug,Account Maintenance Officer,13,2023-04-12,Active
64,UB0465S,David,Amooti,david.amooti465@unitybank.co.ug,Account Maintenance Officer,13,2024-11-24,Active

In [149]:
dim_employee.shape

(65, 8)

##  Generate Customer Dimension

In [150]:
customer_data = []
customer_number = 100001

customer_distribution = {
    "Retail": 350,
    "SME": 100,
    "Corporate": 50
}

occupations = random.choices(
[
"Business Owner",
"Civil Servant",
"Teacher",
"Student",
"Farmer",
"Nurse",
"Engineer",
"Doctor"
],
weights=[20,18,15,12,10,10,8,7],
k=1
)[0]

segments = {
    "Retail": ["Mass Market", "Personal Banking", "Premier"],
    "SME": ["Small Business", "Medium Enterprise"],
    "Corporate": ["Corporate"]
}

cities = [
    "Kampala", "Entebbe", "Mukono", "Jinja",
    "Mbarara", "Gulu", "Lira", "Fort Portal",
    "Hoima", "Soroti", "Tororo", "Kasese"
]

# Specific suffix words to generate localized business/corporate names
sme_suffixes = ["& Sons", "Enterprises", "Traders", "Hardware", "Boutique", "Agro-Supplies", "Investments"]
corporate_suffixes = ["Limited", "PLC", "Group", "Holdings", "Industries", "Logistics", "Telecom"]

In [151]:
for customer_type, number in customer_distribution.items():
    for i in range(number):
        
        customer_id = f"UBC{customer_number}"
        city = random.choice(cities)
        segment = random.choice(segments[customer_type])
        
        # 1. Retail Customers (Individuals)
        if customer_type == "Retail":
            gender = random.choice(["Male", "Female"])
            first_name = random.choice(male_first_names if gender == "Male" else female_first_names)
            last_name = random.choice(male_last_names if gender == "Male" else female_last_names)
            customer_name = f"{first_name} {last_name}"
            dob = fake.date_of_birth(minimum_age=18, maximum_age=70)
            occupation = random.choice(occupations)
            
        # 2. SME Customers (Small Businesses)
        elif customer_type == "SME":
            gender = "Not Applicable"
            # Generates a business name like "Mukasa & Sons" or "Jinja Hardware"
            business_base = random.choice(male_last_names) if random.random() > 0.5 else random.choice(cities)
            customer_name = f"{business_base} {random.choice(sme_suffixes)}"
            dob = fake.date_of_birth(minimum_age=2, maximum_age=15)  # Company registration age
            occupation = "Business Entity"
            
        # 3. Corporate Customers (Large Companies)
        elif customer_type == "Corporate":
            gender = "Not Applicable"
            # Generates a large entity name like "Kampala Holdings Limited"
            corporate_base = random.choice(cities) if random.random() > 0.5 else f"Equator {fake.word().capitalize()}"
            customer_name = f"{corporate_base} {random.choice(corporate_suffixes)}"
            dob = fake.date_of_birth(minimum_age=10, maximum_age=40)  # Established corporations
            occupation = "Corporate Entity"

        customer_data.append([
            customer_id,
            customer_name,
            customer_type,
            gender,
            dob,
            occupation,
            segment,
            city,
            branch_id
        ])

        customer_number += 1

dim_customer = pd.DataFrame(
    customer_data,
    columns=[
        "CustomerID",
        "CustomerName",
        "CustomerType",
        "Gender",
        "DateOfBirth",
        "Occupation",
        "Segment",
        "City",
        "BranchID"
    ]
)

In [152]:
dim_customer.head()

,CustomerID,CustomerName,CustomerType,Gender,DateOfBirth,Occupation,Segment,City,BranchID
0,UBC100001,Sheibah Onyango,Retail,Female,1956-04-07,e,Premier,Gulu,13
1,UBC100002,Michael Isabirye,Retail,Male,1964-11-13,s,Personal Banking,Tororo,13
2,UBC100003,Sharon Galiwango,Retail,Female,2001-08-07,s,Mass Market,Mbarara,13
3,UBC100004,Lisa Akiiki,Retail,Female,1969-07-13,e,Mass Market,Lira,13
4,UBC100005,Danielle Ankunda,Retail,Female,1980-04-03,e,Personal Banking,Gulu,13

##  Generate Product Dimension

In [153]:
product_data = []

product_code = 601

currencies = ["UGX"]

for product in banking_products:

    interest_rate = round(
        random.uniform(product["Rate_Min"], product["Rate_Max"]), 2
    )

    opening_fee = random.randint(
        product["Fee_Min"],
        product["Fee_Max"]
    )

    # Realistic limits by category
    if product["Category"] == "Accounts":
        maximum_limit = random.randint(5_000_000,50_000_000)

    elif product["Category"] == "Savings":
        maximum_limit = random.randint(10_000_000,100_000_000)

    elif product["Category"] == "Loans":
        maximum_limit = random.randint(20_000_000,500_000_000)

    elif product["Category"] == "Cards":
        maximum_limit = random.randint(2_000_000,20_000_000)

    else:
        maximum_limit = random.randint(50_000_000,1_000_000_000)

    product_data.append([

        product_code,

        product["Name"],

        f"{product['Segment']} {product['Category']} product",

        product["Category"],

        opening_fee,

        interest_rate,

        "UGX",

        maximum_limit,

        "Active"

    ])

    product_code += 1

In [154]:
dim_product = pd.DataFrame(

    product_data,

    columns=[

        "ProductCode",

        "ProductName",

        "Description",

        "Category",

        "OpeningFee",

        "InterestRate",

        "Currency",

        "MaximumLimit",

        "ProductStatus"

    ]

)

dim_product.head()

,ProductCode,ProductName,Description,Category,OpeningFee,InterestRate,Currency,MaximumLimit,ProductStatus
0,601,Unity Everyday Checking,Retail Accounts product,Accounts,3989,0.02,UGX,40512677,Active
1,602,Unity Premium Checking,Retail Accounts product,Accounts,13867,0.96,UGX,8060877,Active
2,603,High-Yield Savings,Retail Savings product,Savings,0,5.77,UGX,48734434,Active
3,604,Kiddie Savings Account,Retail Savings product,Savings,0,3.01,UGX,30133683,Active
4,605,Personal Unsecured Loan,Retail Loans product,Loans,84306,18.83,UGX,37015633,Active

##  Generate Date Dimension

In [155]:


date_range = pd.date_range(
    start="2024-01-01",
    end="2026-12-31"
)

dim_date = pd.DataFrame()

dim_date["FullDate"] = date_range

dim_date["DateKey"] = dim_date["FullDate"].dt.strftime("%Y%m%d").astype(int)

dim_date["Day"] = dim_date["FullDate"].dt.day

dim_date["Month"] = dim_date["FullDate"].dt.month

dim_date["MonthName"] = dim_date["FullDate"].dt.month_name()

dim_date["Quarter"] = "Q" + dim_date["FullDate"].dt.quarter.astype(str)

dim_date["Year"] = dim_date["FullDate"].dt.year

dim_date["DayOfWeek"] = dim_date["FullDate"].dt.day_name()

dim_date["IsWeekend"] = dim_date["DayOfWeek"].isin(
    ["Saturday","Sunday"]
)

dim_date = dim_date[
[
"DateKey",
"FullDate",
"Day",
"Month",
"MonthName",
"Quarter",
"Year",
"DayOfWeek",
"IsWeekend"
]
]

In [156]:
dim_date.head()

,DateKey,FullDate,Day,Month,MonthName,Quarter,Year,DayOfWeek,IsWeekend
0,20240101,2024-01-01,1,1,January,Q1,2024,Monday,False
1,20240102,2024-01-02,2,1,January,Q1,2024,Tuesday,False
2,20240103,2024-01-03,3,1,January,Q1,2024,Wednesday,False
3,20240104,2024-01-04,4,1,January,Q1,2024,Thursday,False
4,20240105,2024-01-05,5,1,January,Q1,2024,Friday,False

##  Generate Fact Table (FactCases)

In [157]:


case_data = []

statuses = (
    ["Completed"]*40 +
    ["In Progress"]*30 +
    ["Pending"]*20 +
    ["Returned"]*5 +
    ["Escalated"]*5
)

priorities = (
    ["Medium"]*40 +
    ["High"]*30 +
    ["Low"]*20 +
    ["Critical"]*10
)

queues = [
    "Maker",
    "Checker",
    "Call Back"
]

case_types = [
    "Account Opening",
    "Account Closure",
    "KYC Update",
    "Limit Amendment",
    "Mandate Update"
]

In [158]:
for case in range(1,5001):


    customer = dim_customer.sample(1).iloc[0]

    eligible_products = dim_product[
    dim_product["Description"].str.contains(customer.CustomerType)
]

    product = eligible_products.sample(1).iloc[0]

    employee = dim_employee.sample(1).iloc[0]

    opened = fake.date_between(
        start_date="-2y",
        end_date="today"
    )

    resolution = random.randint(1,10)

    closed = opened + timedelta(days=resolution)

    status = random.choice(statuses)

    case_data.append([
        case,
        f"100{random.randint(1000000,9999999)}",
        customer.CustomerID,
        product.ProductCode,
        employee.BranchID,
        employee.EmployeeID,
        int(opened.strftime("%Y%m%d")),
        int(closed.strftime("%Y%m%d")),
        random.choice(case_types),
        random.choice(queues),
        status,
        random.choice(priorities),
        random.randint(1,5),
        resolution,
        1 if status=="Escalated" else 0
    ])

fact_cases = pd.DataFrame(
    case_data,
    columns=[
        "CaseID",
        "AccountNumber",
        "CustomerID",
        "ProductCode",
        "BranchID",
        "EmployeeID",
        "OpenedDateKey",
        "ClosedDateKey",
        "CaseType",
        "Queue",
        "Status",
        "Priority",
        "SLA_Days",
        "Resolution_Days",
        "Escalated"
    ]
)

In [159]:
fact_cases.head()

,CaseID,AccountNumber,CustomerID,ProductCode,BranchID,EmployeeID,OpenedDateKey,ClosedDateKey,CaseType,Queue,Status,Priority,SLA_Days,Resolution_Days,Escalated
0,1,1005480705,UBC100022,605,12,UB0458S,20241016,20241021,KYC Update,Maker,In Progress,Critical,4,5,0
1,2,1008540261,UBC100391,612,5,UB0437T,20251229,20260104,Account Closure,Maker,Completed,Medium,5,6,0
2,3,1007354979,UBC100051,607,8,UB0449O,20260118,20260124,Mandate Update,Checker,In Progress,High,3,6,0
3,4,1002771343,UBC100257,605,12,UB0461I,20251009,20251019,Limit Amendment,Call Back,Completed,High,4,10,0
4,5,1008857597,UBC100054,608,10,UB0454N,20250304,20250309,Account Closure,Checker,In Progress,Low,5,5,0

##  Exporting all Tables

In [161]:

tables = {

    "DimBranch": dim_branch,
    "DimEmployee": dim_employee,
    "DimCustomer": dim_customer,
    "DimProduct": dim_product,
    "DimDate": dim_date,
    "FactCases": fact_cases

}

for table_name, df in tables.items():

    df.to_csv(f"{table_name}.csv", index=False)

    print(f"✅ {table_name}.csv exported")

✅ DimBranch.csv exported
✅ DimEmployee.csv exported
✅ DimCustomer.csv exported
✅ DimProduct.csv exported
✅ DimDate.csv exported
✅ FactCases.csv exported